.TH "ftpsmartsync" 1 "" ""


.SH NAME

.P
ftpsmartsync \- synchronizes a directory with an FTP host efficiently.

.SH SYNOPSIS

.P
\fBftpsmartsync\fR \-h

.P
\fBftpsmartsync\fR [\-q] [\-s]

.SH DESCRIPTION

.P
\fBftpsmartsync\fR is a program that synchronizes all files beneath the current
directory with an FTP host efficiently.

.P
The destination host is identified by a \fI.ftp_upstream\fR in the current
directory that must have the following line:

.nf
ftp://user@host/path
.fi


.P
The password is found by looking at \fI~/.netrc\fR, see \fBnetrc\fR(5).
If netrc is unavailable, then gnome\-keyring is used. For more information
about gnome\-keyring, please refer to http://wiki.github.com/xrogaan/ftpsync/.

.P
ftpsmartsync sends all files in the current directory to the target host, and stores
the MD5 of the sent files in a \fIhashes.txt\fR files in the remote host. When
syncing again, it checks the MD5 of each file against the one stored in the
remote \fIhashes.txt\fR file, and only sends the files that are different. This
makes ftpsmartsync very efficient when synchronizing a directory with only a few
different files, as long as they are always sent by ftpsmartsync.

.SH OPTIONS

.P
\fB\-h\fR Help.

.P
\fB\-q\fR Quiet mode.

.P
\fB\-s\fR Safe mode: sends hashes.txt after every successful file transfer.

.SH AUTHORS

.P
Originaly written by Leandro Penz (http://lpenz.github.com)

.P
gnome\-keyring and fixes by Bellière Ludovic (http://github.com/xrogaan)

.SH SEE ALSO

.P
\fBftp\fR(1),
\fBnetrc\fR(5)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man -i manual.t2t -o ftpsmartsync.1
