---
name: CI
on: [workflow_dispatch, push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker://lpenz/omnilint:0.5.2
  python:
    uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.9.0
    with:
      coveralls: true
      mypy: false
      docs: false
      publish_pypi: true
      publish_github_release: true
      publish_packagecloud_repository_deb: |
        ["debian/debian/trixie",
         "ubuntu/ubuntu/noble"]
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
